### ISSUE TITLE
[Bug]: vboxsf does not build with 7.3

### ISSUE THREAD

**Issue by jirislaby** [VirtualBox/virtualbox#849]
### Version

trunk/main

### Host OS Type

Linux

### Host OS name + version

openSUSE Tumbleweed

### Host Architecture

x86

### Guest OS Type

all

### Guest Architecture

x86

### Guest OS name + version

does not matter

### Component

Guest Additions/Shared Folders

### What happened?

`vboxsf` does not build against kernel 7.3:
```
[   77s] dirops.c:1416:23: error: initialization of ‘int (*)(struct mnt_idmap *, struct inode *, struct dentry *, umode_t)’ {aka ‘int (*)(struct mnt_idmap *, struct inode *, struct dentry *, short unsigned int)’} from incompatible pointer type ‘int (*)(struct mnt_idmap *, struct inode *, struct dentry *, umode_t,  bool)’ {aka ‘int (*)(struct mnt_idmap *, struct inode *, struct dentry *, short unsigned int,  _Bool)’} [-Wincompatible-pointer-types]
[   77s]  1416 |     .create         = vbsf_inode_create,
[   77s]       |                       ^~~~~~~~~~~~~~~~~
[   77s] dirops.c:1416:23: note: (near initialization for ‘vbsf_dir_iops.create’)
[   77s] dirops.c:1050:12: note: ‘vbsf_inode_create’ declared here
[   77s]  1050 | static int vbsf_inode_create(struct mnt_idmap *idmap, struct inode *parent, struct dentry *dentry, umode_t mode, bool excl)
[   77s]       |            ^~~~~~~~~~~~~~~~~
```

It is due to torvalds/linux@b2f1e6301efa. [This patch](https://github.com/user-attachments/files/31721496/0001-Additions-Linux-vboxsf-Align-with-upstream-vboxsf-ch.patch) fixes the build.

### How can we reproduce this?

Just build against 7.3.

### Did you upload *all* of your necessary log files, screenshots, etc.?

- [x] Yes, I've uploaded all pertinent files to this issue.

**Comment by galitsyn-oracle** [comment]
Please provide full kernel version. Builds here w/ 7.3.0-rc1.

**Comment by alflr** [comment]
Thanks for noting, should be fixed in the tree with the next sync.

**Comment by galitsyn-oracle** [comment]
Still need full kernel version. I've seen this issue w/ 7.3.0-rc0, but it was gone w/ rc1. So far, there is nothing to fix.

**Comment by jirislaby** [comment]
> Still need full kernel version. I've seen this issue w/ 7.3.0-rc0, but it was gone w/ rc1. So far, there is nothing to fix.

It's pure `7.3-rc1`.  There are no other changes to `inode_operations::create`. Nor pre-`rc1`, nor post .

**Comment by jirislaby** [comment]
See:
https://github.com/torvalds/linux/blob/940de590b839f71d6dc846160534bf202401b8b7/include/linux/fs.h#L2002-L2003
