### ISSUE TITLE
[Bug]: virtualbox does not build with kernel 7.0-rc*

### ISSUE THREAD

**Issue by jirislaby** [VirtualBox/virtualbox#582]
### Version

trunk/main

### Host OS Type

Linux

### Host OS name + version

openSUSE Tumbleweed

### Host Architecture

x86

### Guest OS Type

Linux

### Guest Architecture

x86

### Guest OS name + version

n/a

### Component

VMM

### What happened?

The build results in:
```
vbox_fb.c:214:10: error: ‘struct fb_ops’ has no member named ‘fb_debug_enter’
  214 |         .fb_debug_enter = drm_fb_helper_debug_enter,
      |          ^~~~~~~~~~~~~~
vbox_fb.c:214:27: error: ‘drm_fb_helper_debug_enter’ undeclared here (not in a function); did you mean ‘drm_fb_helper_damage_area’?
  214 |         .fb_debug_enter = drm_fb_helper_debug_enter,
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                           drm_fb_helper_damage_area
vbox_fb.c:215:10: error: ‘struct fb_ops’ has no member named ‘fb_debug_leave’
  215 |         .fb_debug_leave = drm_fb_helper_debug_leave,
      |          ^~~~~~~~~~~~~~
vbox_fb.c:215:27: error: ‘drm_fb_helper_debug_leave’ undeclared here (not in a function); did you mean ‘drm_fb_helper_damage_area’?
  215 |         .fb_debug_leave = drm_fb_helper_debug_leave,
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                           drm_fb_helper_damage_area
```

The code:
https://github.com/VirtualBox/virtualbox/blob/581733f208746f45a23e223b9ef5bc862458e220/src/VBox/Additions/linux/drm/vbox_fb.c#L219-L220

The hooks were removed by https://github.com/torvalds/linux/commit/7068d42048dab5eb71a0d65388f64f1e0ca5b9ee:
```
commit 7068d42048dab5eb71a0d65388f64f1e0ca5b9ee
Author: Thomas Zimmermann <[tzimmermann@suse.de](mailto:tzimmermann@suse.de)>
Date:   Tue Nov 25 13:52:17 2025 +0100

    fbcon: Remove fb_debug_enter/_leave from struct fb_ops
```

Vbox needs to adapt, likely remove the hooks.

### How can we reproduce this?

Just build against the newest kernel.

### Did you upload *all* of your necessary log files, screenshots, etc.?

- [x] Yes, I've uploaded all pertinent files to this issue.

**Comment by galitsyn-oracle** [comment]
@jirislaby ,

Errors you are observing are related to the Guest Additions, not to the host package. Errors come from `vboxvideo` kernel driver. This driver will be deprecated for kernels 7.0 (and newer) starting from the next release. This mean that official Guest Additions will still ship driver source code, however its build will be skipped for 7.0+ kernels (older kernels are still supported though). Starting from the next release, users are encouraged to use `vboxvideo` which comes with Linux kernel itself if guest is using VBoxVGA/VBoxSVGA graphics (note, for modern Linux guests it is recommended to use VMSVGA graphics instead). Corresponding fixes are already available on our test builds page (https://www.virtualbox.org/wiki/Testbuilds) for the "Latest 7.2.x test builds" and "Development snapshots".

**Comment by shmerl** [comment]
I see this problem reappearing with kernel 7.1.2. Even using latest test build of guest additions `7.2.11-174340`.

Exact error:

```
# CC [M]  vbox_mode.o
   x86_64-linux-gnu-gcc-15 -Wp,-MMD,./.vbox_mode.o.d -nostdinc 
-I/usr/src/linux-headers-7.1-common/arch/x86/include 
-I/usr/src/linux-headers-7.1-amd64/arch/x86/include/generated 
-I/usr/src/linux-headers-7.1-common/include 
-I/usr/src/linux-headers-7.1-amd64/include 
-I/usr/src/linux-headers-7.1-common/arch/x86/include/uapi 
-I/usr/src/linux-headers-7.1-amd64/arch/x86/include/generated/uapi 
-I/usr/src/linux-headers-7.1-common/include/uapi 
-I/usr/src/linux-headers-7.1-amd64/include/generated/uapi -include 
/usr/src/linux-headers-7.1-common/include/linux/compiler-version.h -include 
/usr/src/linux-headers-7.1-common/include/linux/kconfig.h -include 
/usr/src/linux-headers-7.1-common/include/linux/compiler_types.h -D__KERNEL__ 
-fshort-wchar -funsigned-char -fno-common -fno-PIE -fno-strict-aliasing 
-std=gnu11 -fms-extensions -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx 
-mno-sse4a -fcf-protection=branch -fno-jump-tables -m64 -falign-jumps=1 
-falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 
-mskip-rax-setup -march=x86-64 -mtune=generic -mno-red-zone -mcmodel=kernel 
-mstack-protector-guard-reg=gs 
-mstack-protector-guard-symbol=__ref_stack_chk_guard -Wno-sign-compare 
-fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern 
-mindirect-branch-register -mindirect-branch-cs-prefix 
-mfunction-return=thunk-extern -fno-jump-tables -mharden-sls=all 
-fpatchable-function-entry=16,16 -fno-delete-null-pointer-checks -O2 
-fno-allow-store-data-races -fstack-protector-strong 
-ftrivial-auto-var-init=zero -fzero-init-padding-bits=all 
-fno-stack-clash-protection -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY 
-fmin-function-alignment=16 -fstrict-flex-arrays=3 -fno-strict-overflow 
-fno-stack-check -fconserve-stack -fno-builtin-wcslen -Wall -Wextra -Wundef 
-Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type 
-Werror=strict-prototypes -Wno-format-security -Wno-trigraphs 
-Wno-frame-address -Wno-address-of-packed-member -Wmissing-declarations 
-Wmissing-prototypes -Wframe-larger-than=2048 -Wno-main -Wno-type-limits 
-Wno-dangling-pointer -Wvla-larger-than=1 -Wno-pointer-sign 
-Wcast-function-type -Wno-unterminated-string-initialization -Wno-array-bounds 
-Wno-stringop-overflow -Wno-alloc-size-larger-than -Wimplicit-fallthrough=5 
-Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init 
-Wenum-conversion -Wunused -Wno-unused-but-set-variable 
-Wno-unused-const-variable -Wno-packed-not-aligned -Wno-format-overflow 
-Wno-format-truncation -Wno-stringop-truncation -Wno-override-init 
-Wno-missing-field-initializers -Wno-shift-negative-value 
-Wno-maybe-uninitialized -Wno-sign-compare -Wno-unused-parameter -g 
-DRT_OS_LINUX -I/usr/src/linux-headers-7.1-common/include -I./ 
-I/usr/src/linux-headers-7.1-common/include/drm -D__KERNEL__ -DMODULE 
-DRT_WITHOUT_PRAGMA_ONCE -DRT_ARCH_AMD64  -fsanitize=bounds-strict 
-fsanitize=shift    -DMODULE  -DKBUILD_BASENAME='"vbox_mode"' 
-DKBUILD_MODNAME='"vboxvideo"' -D__KBUILD_MODNAME=vboxvideo -c -o vbox_mode.o 
vbox_mode.c  
vbox_fb.c:216:27: error: ‘drm_fb_helper_debug_leave’ undeclared here (not 
in a function); did you mean ‘drm_fb_helper_damage_area’?
  216 |         .fb_debug_leave = drm_fb_helper_debug_leave,
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                           drm_fb_helper_damage_area
make[3]: *** [/usr/src/linux-headers-7.1-common/scripts/Makefile.build:294: 
vbox_fb.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/src/linux-headers-7.1-common/Makefile:2168: .] Error 2
make[1]: *** [/usr/src/linux-headers-7.1-common/Makefile:260: __sub-make] Error 
2
make: *** [/tmp/vbox.0/Makefile-footer.gmk:146: vboxvideo] Error 2
```

@galitsyn-oracle: is that exclusion somehow fails with kernel 7.1.2?

Any suggestion how to fix this?

UPDATE: it also fails with latest development snapshot.
