### ISSUE TITLE
[Bug]: vboxdrv does not compile with kernel 7.1

### ISSUE THREAD

**Issue by jirislaby** [VirtualBox/virtualbox#703]
### Version

7.2.8

### Host OS Type

Linux

### Host OS name + version

openSUSE Tumbleweed 20260601

### Host Architecture

x86

### Guest OS Type

all

### Guest Architecture

x86

### Component

Host Support

### What happened?

```
[   51s] # CC [M]  linux/SUPDrv-linux.o
[   51s]   gcc -Wp,-MMD,linux/.SUPDrv-linux.o.d ...
[   51s] linux/SUPDrv-linux.c:213:19: error: ‘kvm_enable_virtualization’ undeclared here (not in a function); did you mean ‘kvm_arch_enable_virtualization’?
[   51s]   213 | static __typeof__(kvm_enable_virtualization)   *g_pfnKvmEnableVirtualization;
[   51s]       |                   ^~~~~~~~~~~~~~~~~~~~~~~~~
[   51s]       |                   kvm_arch_enable_virtualization
[   51s] linux/SUPDrv-linux.c:215:19: error: ‘kvm_disable_virtualization’ undeclared here (not in a function); did you mean ‘kvm_arch_disable_virtualization’?
[   51s]   215 | static __typeof__(kvm_disable_virtualization)  *g_pfnKvmDisableVirtualization;
[   51s]       |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
[   51s]       |                   kvm_arch_disable_virtualization
[   51s] linux/SUPDrv-linux.c: In function ‘supdrvOSEnableHwvirt’:
[   51s] linux/SUPDrv-linux.c:1962:24: error: called object ‘g_pfnKvmEnableVirtualization’ is not a function or function pointer
[   51s]  1962 |         int const rc = g_pfnKvmEnableVirtualization();
[   51s]       |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   51s] linux/SUPDrv-linux.c:213:49: note: declared here
[   51s]   213 | static __typeof__(kvm_enable_virtualization)   *g_pfnKvmEnableVirtualization;
[   51s]       |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   51s] linux/SUPDrv-linux.c:1975:9: error: called object ‘g_pfnKvmDisableVirtualization’ is not a function or function pointer
[   51s]  1975 |         g_pfnKvmDisableVirtualization();
[   51s]       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   51s] linux/SUPDrv-linux.c:215:49: note: declared here
[   51s]   215 | static __typeof__(kvm_disable_virtualization)  *g_pfnKvmDisableVirtualization;
[   51s]       |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
These were removed in https://github.com/torvalds/linux//commit/d30372d0b7e637475c79a785d055f4eb8c863656.

### How can we reproduce this?

Build against 7.1 (-rc7 at this point, 7.1 is released next week likely).

### Did you upload *all* of your necessary log files, screenshots, etc.?

- [x] Yes, I've uploaded all pertinent files to this issue.

**Comment by jirislaby** [comment]
This was dropped by b8c6c3683894072f4a8ff910c354c03b65a23464, apparently.

**Comment by galitsyn-oracle** [comment]
Linux kernel 7.1 support will be added in the next maintenance release.

**Comment by ghost** [comment]
a chance we see the support in test builds ?
when ?

**Comment by galitsyn-oracle** [comment]
Test builds should already have the fix.

**Comment by ghost** [comment]
yup, modules compile, but both (test build and developer snapshot from 2026-06-08) crashes here.

box only recoverable via power button. 
afterwards extension is no more installed.

Fedora 44 and homebrewed kernel 7.1


since moons:
cleaning under /opt/ removes all desktop icons.
fixable via:
sudo dnf reinstall shared-mime-info
gnome logout/-in

anyway, thanks for support
