### ISSUE TITLE
[Bug]: Guest Additions 7.2.16 fail to compile on Linux kernel 6.12.107 (drm_fb_helper_alloc_info missing)

### ISSUE THREAD

**Issue by DerHut** [VirtualBox/virtualbox#845]
[vboxadd-setup-error-2026-08-30.txt](https://github.com/user-attachments/files/31620733/vboxadd-setup-error-2026-08-30.txt)

 Version

7.2.16

### Host OS Type

Windows

### Host OS name + version

Windows 10, Build 19045.7663 (22H2)

### Host Architecture

x86

### Guest OS Type

Linux

### Guest Architecture

x86

### Guest OS name + version

LMDE 7  Kernel 6.12.107+deb13-amd64

### Component

Guest Additions/Installer

### What happened?

/tmp/vbox.0/vbox_fb.c:337:16: error: implicit declaration of function ‘drm_fb_helper_alloc_info’; did you mean ‘drm_fb_helper_fill_info’?
/tmp/vbox.0/vbox_fb.c:337:14: error: assignment to ‘struct fb_info *’ from ‘int’ makes pointer from integer without a cast
make[2]: *** [/usr/src/linux-headers-6.12.107+deb13-common/scripts/Makefile.build:234: /tmp/vbox.0/vbox_fb.o] Fehler 1
make[1]: *** [/usr/src/linux-headers-6.12.107+deb13-common/Makefile:1992: /tmp/vbox.0] Error 2
make: *** [/tmp/vbox.0/Makefile-footer.gmk:146: vboxvideo] Error 2

### How can we reproduce this?

1. Host: Windows 10 Build 19045.7663, running VirtualBox 7.2.16.
2. Guest: LMDE 7 with kernel 6.12.107+deb13-amd64 installed and running.
3. Insert Guest Additions CD image (Devices → Insert Guest Additions CD image).
4. Mount the CD and run the installer: sudo /mnt/VBoxLinuxAdditions.run
5. Observe the compilation failure during the graphics driver build.

### Did you upload *all* of your necessary log files, screenshots, etc.?

- [x] Yes, I've uploaded all pertinent files to this issue.
