### ISSUE TITLE
[Bug]: virtualbox does not build with LTS kernel 6.18.44

### ISSUE THREAD

**Issue by rfrohl** [VirtualBox/virtualbox#812]
### Version

7.2.14

### Host OS Type

Linux

### Host OS name + version

openSUSE Tumbleweed

### Host Architecture

x86

### Guest OS Type

other

### Guest Architecture

n/a

### Guest OS name + version

n/a

### Component

Unspecified

### What happened?

With the new kernel LTS release 6.18.44 the kmp build starts failing:

```
[   82s] vbox_fb.c: In function â€˜vboxfb_createâ€™:
[   82s] vbox_fb.c:336:16: error: implicit declaration of function â€˜drm_fb_helper_alloc_infoâ€™; did you mean â€˜drm_fb_helper_fill_infoâ€™? [-Wimplicit-function-declaration]
[   82s]   336 |         info = drm_fb_helper_alloc_info(helper);
[   82s]       |                ^~~~~~~~~~~~~~~~~~~~~~~~
[   82s]       |                drm_fb_helper_fill_info
[   82s] vbox_fb.c:336:14: error: assignment to â€˜struct fb_info *â€™ from â€˜intâ€™ makes pointer from integer without a cast [-Wint-conversion]
[   82s]   336 |         info = drm_fb_helper_alloc_info(helper);
[   82s]       |              ^
[   82s] make[3]: *** [/usr/src/linux-6.18.44-1-longterm/scripts/Makefile.build:287: vbox_fb.o] Error 1
[   82s] make[3]: *** Waiting for unfinished jobs....
```

This is likely due to a [backport from 6.19](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=3f58077457985c622c014f438d8e00dbd03db338) that removes the EXPORT_SYMBOL from drm_fb_helper_alloc_info(). 

I suspect that it would need an adjustment similar to the [6.19 changes](https://github.com/VirtualBox/virtualbox/commit/8fcd1c8ac7d66974dff2e973521f4b7f4a18a52c).

### How can we reproduce this?

building against the new LTS 6.18.44 kernel

### Did you upload *all* of your necessary log files, screenshots, etc.?

- [x] Yes, I've uploaded all pertinent files to this issue.

**Comment by rfrohl** [comment]
Maybe it helps someone, we fixed it with this [patch](https://build.opensuse.org/projects/Virtualization/packages/virtualbox/files/kernel-longterm_6-18-44.patch?expand=1).

There is some uncertainty if there might be functional impact as well, requiring more changes, but this at least fixes the build.

**Comment by Ketrel** [comment]
I'm having this issue on a fresh Debian 13 install with kernel 6.12.105 when it tries to build the kernel modules for guest additions.

Is there any workaround that can be done on the guest with the guest additions media inserted?

**Comment by jlick** [comment]
> Maybe it helps someone, we fixed it with this [patch](https://build.opensuse.org/projects/Virtualization/packages/virtualbox/files/kernel-longterm_6-18-44.patch?expand=1).

Debian 13 latest kernel requires this for the patch to work:

#if RTLNX_VER_MIN(6,12,105) || RTLNX_RHEL_RANGE(9,9, 9,99)

It is probably unsustainable to account for all backported kernels, so a different approach to the patch is probably needed.

**Comment by jlick** [comment]
> I'm having this issue on a fresh Debian 13 install with kernel 6.12.105 when it tries to build the kernel modules for guest additions.
> 
> Is there any workaround that can be done on the guest with the guest additions media inserted?

No need for the guest additions media. That actually makes it more complicated because it unpacks and builds the source on the fly which makes it difficult to patch.

If you already upgraded to 6.12.105 and Guest Additions failed, fix by doing the following:

1) Edit `/opt/VBoxGuestAdditions-*/src/vboxguest-*/vboxvideo/vbox_fb.c` and make the one line change in @rfrohl 's patch with the version changed to 6,12,105
2) Run /sbin/rcvboxadd cleanup
3) Run /sbin/rcvboxadd setup

If you have a VM you didn't yet upgrade, just do step 1 before upgrading the kernel.

The above will persist across future kernel upgrades, but not new installs of Guest Additions.

**Comment by jlick** [comment]
> It is probably unsustainable to account for all backported kernels, so a different approach to the patch is probably needed.

Based on some research, the "info = helper->info;" syntax was added in Linux Kernel 6.2.0, so it should be safe to change the patch to use 6,2,0 as the minimum version instead of 6,18,44 when the old syntax was removed. This may still pose a problem if older kernels get backported patches.

**Comment by galitsyn-oracle** [comment]
Please update to the latest Guest Additions.

**Comment by Ketrel** [comment]
> > I'm having this issue on a fresh Debian 13 install with kernel 6.12.105 when it tries to build the kernel modules for guest additions.
> > Is there any workaround that can be done on the guest with the guest additions media inserted?
> 
> No need for the guest additions media. That actually makes it more complicated because it unpacks and builds the source on the fly which makes it difficult to patch.
> 
> If you already upgraded to 6.12.105 and Guest Additions failed, fix by doing the following:
> 
>     1. Edit `/opt/VBoxGuestAdditions-*/src/vboxguest-*/vboxvideo/vbox_fb.c` and make the one line change in [@rfrohl](https://github.com/rfrohl) 's patch with the version changed to 6,12,105
> 
>     2. Run /sbin/rcvboxadd cleanup
> 
>     3. Run /sbin/rcvboxadd setup
> 
> 
> If you have a VM you didn't yet upgrade, just do step 1 before upgrading the kernel.
> 
> The above will persist across future kernel upgrades, but not new installs of Guest Additions.

That did work, but note, I didn't upgrade TO 6.12.105, this was a fresh Debian 13 install.  That's what it started with.
