### ISSUE TITLE
[Bug]: Apt installation build error "VBox/cdefs.h: No such file or directory"

### ISSUE THREAD

**Issue by Lightning11wins** [VirtualBox/virtualbox#554]
### Version

trunk/main

### Host OS Type

Linux

### Host OS name + version

Linux Mint 22.3 (aka. Ubuntu 24.04.3 LTS / Linux Kernel 6.17.0-14-generic)

### Host Architecture

ARM

### Guest OS Type

all

### Guest Architecture

ARM

### Guest OS name + version

Any

### Component

Other

### What happened?

A compiler error occurs when attempting to install VirtualBox using apt, displaying the following in the command prompt (if using apt via a command prompt):
```bash
Error! Bad return status for module build on kernel: 6.17.0-14-generic (x86_64)
Consult /var/lib/dkms/virtualbox/7.0.16/build/make.log for more information.
```

`/var/lib/dkms/virtualbox/7.0.16/build/make.log` contains:
```bash
DKMS make.log for virtualbox-7.0.16 for kernel 6.17.0-14-generic (x86_64)
Mon Feb 16 10:35:28 AM MST 2026
make: Entering directory '/usr/src/linux-headers-6.17.0-14-generic'
make[1]: Entering directory '/var/lib/dkms/virtualbox/7.0.16/build'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  CC [M]  vboxdrv/linux/SUPDrv-linux.o
  CC [M]  vboxdrv/SUPDrv.o
  CC [M]  vboxdrv/SUPDrvGip.o
  CC [M]  vboxdrv/SUPDrvSem.o
  CC [M]  vboxdrv/SUPDrvTracer.o
  CC [M]  vboxdrv/SUPLibAll.o
  CC [M]  vboxdrv/common/string/strformatrt.o
  CC [M]  vboxdrv/combined-agnostic1.o
In file included from vboxdrv/linux/SUPDrv-linux.c:42:
vboxdrv/linux/../SUPDrvInternal.h:47:10: fatal error: VBox/cdefs.h: No such file or directory
   47 | #include <VBox/cdefs.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.0-14-generic/scripts/Makefile.build:287: vboxdrv/linux/SUPDrv-linux.o] Error 1
make[4]: *** Waiting for unfinished jobs....
In file included from vboxdrv/SUPDrv.c:43:
vboxdrv/SUPDrvInternal.h:47:10: fatal error: VBox/cdefs.h: No such file or directory
   47 | #include <VBox/cdefs.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.0-14-generic/scripts/Makefile.build:287: vboxdrv/SUPDrv.o] Error 1
In file included from vboxdrv/SUPDrvGip.c:43:
vboxdrv/SUPDrvInternal.h:47:10: fatal error: VBox/cdefs.h: No such file or directory
   47 | #include <VBox/cdefs.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.0-14-generic/scripts/Makefile.build:287: vboxdrv/SUPDrvGip.o] Error 1
In file included from vboxdrv/SUPDrvSem.c:43:
vboxdrv/SUPDrvInternal.h:47:10: fatal error: VBox/cdefs.h: No such file or directory
   47 | #include <VBox/cdefs.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.0-14-generic/scripts/Makefile.build:287: vboxdrv/SUPDrvSem.o] Error 1
vboxdrv/SUPLibAll.c:41:10: fatal error: VBox/sup.h: No such file or directory
   41 | #include <VBox/sup.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.0-14-generic/scripts/Makefile.build:287: vboxdrv/SUPLibAll.o] Error 1
In file included from vboxdrv/SUPDrvTracer.c:43:
vboxdrv/SUPDrvInternal.h:47:10: fatal error: VBox/cdefs.h: No such file or directory
   47 | #include <VBox/cdefs.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.0-14-generic/scripts/Makefile.build:287: vboxdrv/SUPDrvTracer.o] Error 1
vboxdrv/combined-agnostic1.c:38:10: fatal error: internal/iprt.h: No such file or directory
   38 | #include "internal/iprt.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
vboxdrv/common/string/strformatrt.c:42:10: fatal error: iprt/string.h: No such file or directory
   42 | #include <iprt/string.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.0-14-generic/scripts/Makefile.build:287: vboxdrv/combined-agnostic1.o] Error 1
make[4]: *** [/usr/src/linux-headers-6.17.0-14-generic/scripts/Makefile.build:287: vboxdrv/common/string/strformatrt.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.17.0-14-generic/scripts/Makefile.build:556: vboxdrv] Error 2
make[2]: *** [/usr/src/linux-headers-6.17.0-14-generic/Makefile:2016: .] Error 2
make[1]: *** [/usr/src/linux-headers-6.17.0-14-generic/Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/virtualbox/7.0.16/build'
make: *** [Makefile:248: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.17.0-14-generic'
```

It appears that the file `VBox/cdefs.h` is not properly included or does not exist. If there are any other files you would like me to send, please let me know!

**Note**: VirtualBox does _appear_ to be fully functional even with this installation error. However, commands on my system such as `sudo apt upgrade` fail, continuing to give the same error as initially.

### How can we reproduce this?

On my machine, I reproduce this error by first clearing any VirtualBox installation using:
```bash
sudo apt remove --purge virtualbox virtualbox-*
sudo apt autoremove
sudo dpkg --configure -a
```

Then, I install VirtualBox with:
```bash
sudo apt update
sudo apt install virtualbox
```

Both commands log a lot of text, the latter including the log message mentioned above:
```log
Error! Bad return status for module build on kernel: 6.17.0-14-generic (x86_64)
Consult /var/lib/dkms/virtualbox/7.0.16/build/make.log for more information.
```
And checking the indicated log file shows the errors mentioned above.

### Did you upload *all* of your necessary log files, screenshots, etc.?

- [x] Yes, I've uploaded all pertinent files to this issue.

**Comment by galitsyn-oracle** [comment]
@Lightning11wins,

We do not support dkms for quite long time already. VirtualBox-7.0 is also out of support. Please file a bug report to the Linux distribution you are using or switch to repository from virtualbox.org (see https://www.virtualbox.org/wiki/Linux_Downloads for details).

**Comment by Lightning11wins** [comment]
Oh! I had no idea that I was using such an outdated version. Reinstalling using the correct package fixed this issue, as well as several other annoyances I was having.

Thank you so much, and sorry for bothering you!
