### ISSUE TITLE
[Bug]: Noble package repo suggests 7.0.x version which does not work on HWE 6.17 kernel

### ISSUE THREAD

**Issue by jglick** [VirtualBox/virtualbox#535]
### Version

Other or before v7.1.0

### Host OS Type

Linux

### Host OS name + version

Ubuntu 24.04.3 LTS; currently running 6.14.0-37-generic, installing 6.17.0-14-generic

### Host Architecture

x86

### Guest OS Type

all

### Guest Architecture

x86

### Component

Other

### What happened?

I have my sources defined as

```
deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian noble contrib
```

which I think matches what https://www.virtualbox.org/wiki/Linux_Downloads recommends. Yet

```console
$ apt show virtualbox
Package: virtualbox
Version: 7.0.16-dfsg-2ubuntu1.1
…
```

rather than a current 7.2.x version. I guess because that is listed first in https://download.virtualbox.org/virtualbox/debian/dists/noble/contrib/binary-amd64/Packages ? But it seems 7.0.x does not work on the new kernel (which was just released to Noble users); trying to upgrade my kernel failed with numerous DKMS errors such as

```
vboxdrv/SUPDrvInternal.h:47:10: fatal error: VBox/cdefs.h: No such file or directory
```

Workaround:

```
sudo apt remove virtualbox virtualbox-dkms virtualbox-qt
sudo apt install virtualbox-7.2
```

Seems to work after rebooting into the new kernel.

Should the package repo suggest 7.2?

### How can we reproduce this?

Not sure what to do to reproduce from scratch; this is an upgrade scenario with a system which has been installed for a long time.

### Did you upload *all* of your necessary log files, screenshots, etc.?

- [x] Yes, I've uploaded all pertinent files to this issue.

**Comment by galitsyn-oracle** [comment]
Hi @jglick ,

Repositories at https://download.virtualbox.org/virtualbox provide packages named as "virtualbox-X.Y". Package you are referring to (without version numbers in its name) is provided by your distribution. If you would like to get info about packages provided by us, try "apt show virtualbox-7.2" for example.

**Comment by jglick** [comment]
Ah I somehow missed

```console
$ apt show virtualbox
…
APT-Sources: http://us.archive.ubuntu.com/ubuntu noble-updates/multiverse amd64 Packages
…
$ apt show virtualbox-7.2
…
APT-Sources: https://download.virtualbox.org/virtualbox/debian noble/contrib amd64 Packages
…
```

So this is in fact due to a poor packaging decision on the part of Ubuntu Multiverse maintainers. Sorry for the noise and thank you for the prompt response.
